version: '3.0'

services:
  db:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=Pass2020!
    ports:
      - '5432:5432'
    volumes:
      - ./postgres/schema.sql:/docker-entrypoint-initdb.d/schema.sql

volumes:
  app-volume: #

